apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: gke-dev-to-prod-app
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: gcr.io/kenthua-core/gke-flask-app
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
# deploy:
#   kustomize:
#     paths:
#     - https://github.com/kenthua/gke-dev-to-prod-blueprints?ref=main
profiles:
- name: dev
  deploy:
    kustomize:
      paths:
      - ../config
- name: prod
  deploy:
    kustomize:
      paths:
      - https://github.com/kenthua/gke-dev-to-prod-blueprints/overlays/prod?ref=main